title: Hector Robles
subtitle: This is my online CV and personal blog :)
description: >- # this means to ignore newlines until "baseurl:"
  Hector290601- WebPage :)

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Blog
    url: /blog
  - text: Gallery
    url: /gallery
  - text: Shop
    url : /shop
  - text: Contact
    url : /contact
  - text: Styleguide
    url: /styleguide
  - text: Get Started
    url: /get-started

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: yo.png
author: H茅ctor Robles
author_bio: Hi, my name is H茅ctor Robles. I built this site using devlopr-jekyll, I love python programming, OpenCV development and teach others :D
author_email: "robletes062901@gmail.com"
author_location: Mexico
author_website_url: "https://github.com/Hector290601"
typewrite-text: I麓m a Computer Engineering student, web and desktop developer :)

# Experiences
author_work_experiences:
  - company_name: Colegio de Ciencias y Humanidades Plantel Sur, UNAM
    company_logo: CCHS.png
    company_url: https://www.cch-sur.unam.mx/
    designation: Teacher
    description: Planificaci贸n de clases -Profesor de cursos intensivos -Observaci贸n y evaluaci贸n de cada uno de los alumnos -Facilidad comunicativa y entendimiento con los alumnos.
    visibility: true
  - company_name: Colegio de Ciencias y Humanidades Plantel Sur, UNAM
    company_logo: CCHS.png
    company_url: https://www.cch-sur.unam.mx/
    designation: student advisor
    description: Planificaci贸n de clases -Profesor de cursos intensivos -Observaci贸n y evaluaci贸n de cada uno de los alumnos -Facilidad comunicativa y entendimiento con los alumnos.
    visibility: true
  - company_name: Tribunal de Justicia Administrativa de la ciudad de M茅xico
    company_logo: tjacdmx.png
    company_url: https://www.tjacdmx.gob.mx/
    designation: Programming intern
    description: Web developer.
    visibility: true
  - company_name: Tribunal de Justicia Administrativa de la ciudad de M茅xico
    company_logo: tjacdmx.png
    company_url: https://www.tjacdmx.gob.mx/
    designation: Technical support intern
    description: Assembly and repair of microcomputer equipment, expansion of computer equipment.
    visibility: true

# Education
author_education_details:
  - college_logo: unam.png
    college_name: UNAM
    college_url: https://www.unam.mx/
    college_degree: Computer Engineering Student
    description: Currently studying computer engineering :)
    visibility: true
  - college_logo: unam.png
    college_name: UNAM
    college_url: https://www.unam.mx/
    college_degree: Computer systems, software development
    description: TSU
    visibility: true
  - college_logo: unam.png
    college_name: UNAM
    college_url: https://www.unam.mx/
    college_degree: Maintenance of microcomputing systems
    description: TSU
    visibility: true

# Projects
#author_project_details:
#              - project_thumbnail: gamershub.png
#                project_title: Gamers Hub
#                project_description: A Platform built for Gamers and Game Devs
#                project_url: https://gamershub.in
#                visibility: false
#              - project_thumbnail: hack4r.PNG
#                project_title: Hack4r
#                project_description: A Platform built for Hackers and Penetration Testers
#                project_url: https://hack4r.com
#                visibility: false

# social links
twitter_username: Robletes06290
github_username:  Hector290601
facebook_username: hector290601
linkedin_username: h茅ctor-robles-8a94341ba
behance_username: Robletes0629
instagram_username: hector.robletes.062901
medium_username: robletes062901
telegram_username: Hector290601
dribbble_username: Hector290601
flickr_username: robletes062901

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 4018

# wakatime username (coding activity)
wakatime_username: Hector290601

# mailchimp embedded form url (newsletter):
mailchimp_form_url:  https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: robletes062901@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
